Adding File-dialog
asc-community/MxEngine pull request #24
Opened 2020-10-13 18:24 UTC by JijaLoqie

2020-10-13 20:42 UTC, MomoDeve requested changes

2020-10-13 20:42 UTC, MomoDeve commented on src/Utilities/FileSystem/FileManager.cpp
> +    MxString FileManager::OpenFileDialog()
add the ability to pass filter string as parameter to OpenFileDialog

2020-10-13 20:42 UTC, MomoDeve commented on src/Utilities/FileSystem/FileManager.cpp
> +    MxString FileManager::OpenFileDialogForMesh()
this should not be a separate function

2020-10-13 20:42 UTC, MomoDeve commented on src/Utilities/FileSystem/FileManager.cpp
> +    MxString FileManager::OpenFileDialog()
add the ability to specify start directory. not just `.`

2020-10-13 20:42 UTC, MomoDeve commented on src/Utilities/ImGui/Editors/ResourceEditor.cpp
> +                path = FileManager::OpenFileDialog();
make `path` local variable (see all cases)

2020-10-13 20:42 UTC, MomoDeve commented on CMakeLists.txt
> +    add_subdirectory(samples/Dimon)
delete this sample from pull request

2020-10-17 17:53 UTC, WhiteBlackGoose reviewed
I'm not a cpper, but I have a few feelings...

2020-10-17 17:53 UTC, WhiteBlackGoose commented on src/Utilities/FileSystem/FileManager.cpp
> +        }
Wouldn't it be a better idea to pass this selection as an argument to the function?

2020-10-17 17:53 UTC, WhiteBlackGoose commented on src/Utilities/FileSystem/FileManager.cpp
> -    MxString FileManager::OpenFileDialogForMesh()
I feel like this function was OK, it just should call `OpenFileDialog` with an appropriate selection

2020-10-17 17:53 UTC, WhiteBlackGoose commented on src/Utilities/ImGui/Editors/ComponentEditors/RenderingEditors.cpp
> +			path = FileManager::OpenFileDialog(1);
1 for bool -____-

2020-10-17 18:30 UTC, WhiteBlackGoose reviewed
Nice, I like it more

2020-10-17 18:30 UTC, WhiteBlackGoose commented on src/Utilities/ImGui/Editors/ResourceEditor.cpp
> +            MxString path = FileManager::OpenFileDialog("*.png *.jpg *.jpeg *.bmp *.tga *.hdr");
If you ask me, I'd either abstract it in another function like `OpenFileDialogImage` or make a constant, especially if you use this string multiple times

2020-10-17 18:30 UTC, WhiteBlackGoose commented on src/Utilities/FileSystem/FileManager.h
> +        static MxString OpenFileDialog(const std::string& types);
Shouldn't we stick to `MxString`?

2020-10-21 22:44 UTC, merged